# .github/workflows/display.yaml

name: display

on: workflow_dispatch

jobs:
  # This workflow contains a single job called "display-time"
  display-time:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: display current time
        run: echo "Current time is $(date)"
