name: Variables, Secrets, and Context Showcase

on: workflow_dispatch  # Manual trigger

env:
  GLOBAL_ENV_VAR: "I am a global environment variable"

jobs:
  showcase:
    runs-on: ubuntu-latest

    env:
      JOB_ENV_VAR: "I am a job-level env variable"

    steps:
      - name: Step 1 - Display Environment Variables
        env:
          STEP_ENV_VAR: "I am a step-level env variable"
        run: |
          echo "Global ENV: $GLOBAL_ENV_VAR"
          echo "Job ENV: $JOB_ENV_VAR"
          echo "Step ENV: $STEP_ENV_VAR"

      - name: Step 2 - Display Repository Variables
        run: echo "Repository Variable:\ ${{ vars.REPO_VAR }}"
      
      - name: Step 3 - Display Secrets
        run: echo "Secret Value (masked):\ ${{ secrets.MY_SECRET }}"

      - name: Step 4 - GitHub Context
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Actor (Who triggered it): ${{ github.actor }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Ref (branch or tag): ${{ github.ref }}"
          echo "Run ID: ${{ github.run_id }}"

      - name: Step 5 - Event Context
        run: |
          echo "Event Action: ${{ github.event.action }}"
          echo "Repository Owner: ${{ github.event.repository.owner.login }}"
          echo "Issue Number (if applicable): ${{ github.event.issue.number }}"

      - name: Step 6 - Job Context
        run: |
          echo "Job ID: ${{ job.id }}"
          echo "Job Status: ${{ job.status }}"

      - name: Step 7 - Step Context
        id: example_step
        run: echo "step_output=Hello from Step Context" >> $GITHUB_OUTPUT

      - name: Step 8 - Use Step Output
        run: echo "Step Output:\ ${{ steps.example_step.outputs.step_output }}"
