# .github/workflows/lab3.yml
name: Basic CI Pipeline

on: 
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  print-time:
    runs-on: ubuntu-latest
    env:
      USERNAME: "Naghme"
      PASSWORD: ${{secrets.PASSWORD}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display time with greeting
        run: |
          echo "Good day ${{ env.USERNAME }}!;You logged in with ${{ env.PASSWORD }}.;The current time in  is $(date -u)"
