name: Workflow Commands

on: workflow_dispatch

jobs:
  test-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Set an environment variable
        run: echo "MY_NAME=Naghme" >> $GITHUB_ENV

      - name: Use the environment variable
        run: echo "Hello, my name is $MY_NAME"

      - name: Generate output
        id: example_step
        run: echo "greeting=Hello from workflow commands!" >> $GITHUB_OUTPUT

      - name: Use the output
        run: echo "Message: ${{ steps.example_step.outputs.greeting }}"

      - name: Add debug, notice, and warning messages
        run: |
          echo "::debug::Debug message"
          echo "::notice::This is a notice"
          echo "::warning::This is a warning"
          echo "::error::This is an error"
      
      - name: Mask a secret
        run: |
          echo "::add-mask::super-secret-password"
          echo "Secret value: super-secret-password"
