name: Advanced GitHub Actions Demo

on:
  workflow_dispatch: 

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create a sample file
        run: echo "Hello, GitHub Actions!" > example.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: example-artifact
          path: example.txt

  container-job:
    runs-on: ubuntu-latest
    needs: setup 
    container: node:18  # Running inside a Node.js container
    services:
      redis:
        image: redis  # Running Redis as a service container
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: example-artifact

      - name: Check Redis connection
        run: redis-cli -h redis ping  # Should return "PONG"

      - name: Read artifact content
        run: cat example.txt

  deploy:
    runs-on: ubuntu-latest
    needs: container-job
    environment: 
      name: production 
      url: https://github.com
    concurrency: deploy-env  # Ensures only one deployment runs at a time
    steps:
      - name: Deploy Application
        run: echo "Deploying to production..."
